// @polsia:user-owned — server-only SMS abstraction (Phase 2).
//
// Vendor-agnostic seam: @/lib/auth's phoneNumber plugin only ever calls
// sendOtpSms(); which vendor actually delivers the message is decided here
// by the SMS_PROVIDER env var. Adding another vendor means implementing
// SmsProvider and registering it in resolveProvider() — nothing in
// @/lib/auth changes.
//
// Providers:
//   - unset / "console": logs the code to the server console. Development
//     only — refused outright in production so a missing config can never
//     look like a working sign-in.
//   - "msg91": MSG91's OTP API (India-first, DLT-compliant). INERT until
//     SMS_PROVIDER=msg91 AND its credentials are set; nothing is sent, and
//     no account is contacted, unless an operator opts in. Required env:
//       MSG91_AUTH_KEY          MSG91 dashboard → API → Authkey (secret)
//       MSG91_OTP_TEMPLATE_ID   the DLT-approved OTP template's MSG91 id
//     See .env.example for the full setup notes.
import 'server-only';

export interface SmsProvider {
  /** Deliver a one-time code to `to` (E.164, e.g. "+919876543210"). Must throw on failure. */
  sendOtp(to: string, code: string): Promise<void>;
}

/**
 * Minutes an OTP stays valid. Passed to providers whose templates state the
 * validity window. MUST match `expiresIn` on the phoneNumber plugin in
 * @/lib/auth (currently 10 minutes).
 */
export const OTP_EXPIRY_MINUTES = 10;

const consoleProvider: SmsProvider = {
  async sendOtp(to, code) {
    // biome-ignore lint/suspicious/noConsole: dev-only stand-in; refused in production (see resolveProvider).
    console.log(`[sms:dev] to=${to} code=${code}`);
  },
};

// ---------------------------------------------------------------------------
// MSG91
// ---------------------------------------------------------------------------

const MSG91_OTP_ENDPOINT = 'https://control.msg91.com/api/v5/otp';
const MSG91_TIMEOUT_MS = 10_000;

export interface Msg91Config {
  authKey: string;
  templateId: string;
}

/**
 * MSG91 "Send OTP" (v5). The OTP value is generated by better-auth and passed
 * through (`otp`), so better-auth stays the single source of truth for what
 * code is valid — MSG91 only delivers it. The auth key travels in a header
 * (never the URL, which would end up in access logs).
 *
 * `fetchImpl` is injectable for unit tests.
 */
export function createMsg91Provider(
  config: Msg91Config,
  fetchImpl: typeof fetch = fetch,
): SmsProvider {
  return {
    async sendOtp(to, code) {
      // MSG91 wants the number with country code and no leading "+".
      const mobile = to.replace(/^\+/, '');
      const url = new URL(MSG91_OTP_ENDPOINT);
      url.searchParams.set('template_id', config.templateId);
      url.searchParams.set('mobile', mobile);
      url.searchParams.set('otp', code);
      url.searchParams.set('otp_expiry', String(OTP_EXPIRY_MINUTES));

      let res: Response;
      try {
        res = await fetchImpl(url, {
          method: 'POST',
          headers: {
            authkey: config.authKey,
            accept: 'application/json',
            'content-type': 'application/json',
          },
          body: '{}',
          signal: AbortSignal.timeout(MSG91_TIMEOUT_MS),
        });
      } catch (cause) {
        throw new Error('MSG91 request failed (network/timeout)', { cause });
      }

      // MSG91 answers 200 with {"type":"success"|"error","message":"..."}.
      // Never include the OTP or auth key in this error text.
      const body = (await res.json().catch(() => null)) as {
        type?: string;
        message?: string;
      } | null;
      if (!res.ok || body?.type !== 'success') {
        throw new Error(
          `MSG91 rejected the OTP request (HTTP ${res.status}${
            body?.message ? `: ${body.message}` : ''
          })`,
        );
      }
    },
  };
}

function readMsg91Config(): Msg91Config {
  const authKey = process.env.MSG91_AUTH_KEY;
  const templateId = process.env.MSG91_OTP_TEMPLATE_ID;
  const missing = [!authKey && 'MSG91_AUTH_KEY', !templateId && 'MSG91_OTP_TEMPLATE_ID'].filter(
    Boolean,
  );
  if (!authKey || !templateId) {
    throw new Error(`SMS_PROVIDER=msg91 requires ${missing.join(' and ')} to be set.`);
  }
  return { authKey, templateId };
}

// ---------------------------------------------------------------------------

function resolveProvider(): SmsProvider {
  const configured = process.env.SMS_PROVIDER?.trim().toLowerCase();
  if (!configured || configured === 'console') {
    if (process.env.NODE_ENV === 'production') {
      throw new Error(
        'SMS_PROVIDER is not configured. Phone sign-in cannot send real OTPs in production until SMS_PROVIDER (e.g. "msg91") and its credentials are set.',
      );
    }
    return consoleProvider;
  }
  if (configured === 'msg91') {
    return createMsg91Provider(readMsg91Config());
  }
  throw new Error(`Unknown SMS_PROVIDER "${configured}" — no implementation registered.`);
}

export async function sendOtpSms(phoneNumber: string, code: string): Promise<void> {
  const provider = resolveProvider();
  try {
    await provider.sendOtp(phoneNumber, code);
  } catch (error) {
    // Surface the real cause in the server logs (Render) — the client only
    // ever sees a generic 500, which is otherwise undiagnosable.
    // biome-ignore lint/suspicious/noConsole: operational logging for a failed SMS send; contains no secrets/OTP.
    console.error('[sms] OTP delivery failed:', error instanceof Error ? error.message : error);
    throw error;
  }
}
